
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 16;
  public static final int MULTIPLICAR = 29;
  public static final int CHAR = 18;
  public static final int ENTERO = 7;
  public static final int DOUBLE = 17;
  public static final int RESTA = 28;
  public static final int PIE = 49;
  public static final int TITULOY = 46;
  public static final int LINEAL = 53;
  public static final int TITULOX = 45;
  public static final int EJEY = 44;
  public static final int RPRINT = 2;
  public static final int EJEX = 43;
  public static final int IGUAL = 12;
  public static final int BARRAS = 41;
  public static final int ARROBA = 24;
  public static final int TITULO = 42;
  public static final int ENDPROGRAM = 14;
  public static final int GUION = 21;
  public static final int SUMA = 27;
  public static final int ID = 10;
  public static final int EXCL = 3;
  public static final int MEDIANA = 33;
  public static final int EOF = 0;
  public static final int PARIZQ = 5;
  public static final int error = 1;
  public static final int PROGRAM = 13;
  public static final int FLECHADERECHA = 20;
  public static final int COMA = 11;
  public static final int CADENA = 8;
  public static final int VALUES = 51;
  public static final int MODULO = 31;
  public static final int MENOR = 37;
  public static final int MODA = 34;
  public static final int MAYOR = 36;
  public static final int FLECHA = 19;
  public static final int DIVIDIR = 30;
  public static final int GRAPPIE = 52;
  public static final int VARIANZA = 35;
  public static final int GRAPBAR = 48;
  public static final int END = 22;
  public static final int ARR = 23;
  public static final int MEDIA = 32;
  public static final int CORC = 26;
  public static final int EXEC = 47;
  public static final int PARDER = 4;
  public static final int CORA = 25;
  public static final int LABEL = 50;
  public static final int COLUMNA = 40;
  public static final int VAR = 15;
  public static final int GRAPLINE = 54;
  public static final int PRINT = 39;
  public static final int CONSOLE = 38;
  public static final int PYC = 6;
  public static final int MAS = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RPRINT",
  "EXCL",
  "PARDER",
  "PARIZQ",
  "PYC",
  "ENTERO",
  "CADENA",
  "MAS",
  "ID",
  "COMA",
  "IGUAL",
  "PROGRAM",
  "ENDPROGRAM",
  "VAR",
  "DOSPUNTOS",
  "DOUBLE",
  "CHAR",
  "FLECHA",
  "FLECHADERECHA",
  "GUION",
  "END",
  "ARR",
  "ARROBA",
  "CORA",
  "CORC",
  "SUMA",
  "RESTA",
  "MULTIPLICAR",
  "DIVIDIR",
  "MODULO",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAYOR",
  "MENOR",
  "CONSOLE",
  "PRINT",
  "COLUMNA",
  "BARRAS",
  "TITULO",
  "EJEX",
  "EJEY",
  "TITULOX",
  "TITULOY",
  "EXEC",
  "GRAPBAR",
  "PIE",
  "LABEL",
  "VALUES",
  "GRAPPIE",
  "LINEAL",
  "GRAPLINE"
  };
}

